DROP TABLE IF EXISTS endpoint_hits;

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(512),
    uri       VARCHAR(512),
    ip        VARCHAR(512),
    timestamp TIMESTAMP
);
