DROP TABLE IF EXISTS categories, compilations, events, events_users, locations, users CASCADE;

CREATE TABLE categories
(
    category_id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    category_name VARCHAR(64)
);

CREATE TABLE compilations
(
    compilation_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    pinned         BOOLEAN,
    title          VARCHAR(64)
);

CREATE TABLE locations
(
    location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    UNIQUE (lat, lon)
);

CREATE TABLE users
(
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email   VARCHAR(64),
    name    VARCHAR(128)
);


CREATE TABLE events
(
    event_id           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(512),
    category_id        INT REFERENCES categories (category_id),
    confirmed_requests INT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(512),
    event_date         DATE,
    initiator_id       INT REFERENCES users(user_id),
    location_id        INT REFERENCES locations(location_id),
    paid               BOOLEAN,
    participant_limit  INT,
    published_in       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(64),
    title              INT,
    views              INT

);

CREATE TABLE events_users
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     INT REFERENCES events(event_id),
    requester_id INT REFERENCES users(user_id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(64),
    UNIQUE (event_id, requester_id)
);

