DROP TABLE IF EXISTS categories, compilations, events, events_users, locations, users CASCADE;

CREATE TABLE categories
(
    id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(64)
);

CREATE TABLE compilations
(
    id     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    pinned BOOLEAN,
    title  VARCHAR(64)
);

CREATE TABLE users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email VARCHAR(64),
    name  VARCHAR(128)
);

CREATE TABLE locations
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat FLOAT                                            NOT NULL,
    lon FLOAT                                            NOT NULL
);



CREATE TABLE events
(
    id                 INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(512),
    category_id        INT REFERENCES categories (id),
    confirmed_requests INT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(512),
    event_date         DATE,
    initiator_id       INT REFERENCES users (id),
    location_id        INT REFERENCES locations (id),
    paid               BOOLEAN,
    participant_limit  INT,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(64),
    title              VARCHAR(256),
    views              INT

);

CREATE TABLE IF NOT EXISTS "events_compilations"
(
    event_id       INT REFERENCES events (id),
    compilation_id INT REFERENCES compilations (id),
    UNIQUE (event_id, compilation_id)
);

CREATE TABLE events_users
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     INT REFERENCES events (id),
    requester_id INT REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(64),
    UNIQUE (event_id, requester_id)
);

