version: '3.8'
services:
  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    image: stats-image

    container_name: stats-server-container
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_SERVICE_URL=http://server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:15.2-alpine
    container_name: stats-db
    ports:
      - "127.0.0.1:6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    ports:
      - "127.0.0.1:8080:8080"
    build:
      context: .
      dockerfile: main-service/Dockerfile
    image: ewm-service
    container_name: ewm-service-container
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://127.0.0.1:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db

  ewm-db:
    image: postgres:15.2-alpine
    container_name: ewm-db
    ports:
      - "127.0.0.1:6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#volumes:
#  stats-db:
#  ewm-db: